# Generated by Django 5.2.8 on 2025-11-23 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_crop'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Crop',
            new_name='CropType',
        ),
    ]
