# Generated by Django 5.2.8 on 2025-11-23 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_rename_crop_croptype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='croptype',
            old_name='grow_time_hours',
            new_name='grow_time_seconds',
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planted_at', models.DateTimeField(blank=True, null=True)),
                ('harvest_ready_at', models.DateTimeField(blank=True, null=True)),
                ('crop_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.croptype')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='game.farm')),
            ],
        ),
    ]
