# Generated by Django 5.2.8 on 2025-11-23 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_rename_grow_time_hours_croptype_grow_time_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='x',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plot',
            name='y',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
