# Generated by Django 5.2.8 on 2025-11-23 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_plot_x_plot_y'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('crop_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.croptype')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='game.farm')),
            ],
            options={
                'unique_together': {('farm', 'crop_type')},
            },
        ),
    ]
