# Generated by Django 5.2.8 on 2025-11-24 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='unlocks_crop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlocking_contracts', to='game.croptype'),
        ),
        migrations.AddField(
            model_name='farm',
            name='unlocked_crops',
            field=models.ManyToManyField(blank=True, related_name='farms_unlocked', to='game.croptype'),
        ),
    ]
