# Generated by Django 5.2.8 on 2025-11-24 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_marketlisting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketlisting',
            old_name='quantity_remaining',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='marketlisting',
            name='quantity_total',
        ),
    ]
