# Generated by Django 5.2.8 on 2025-11-24 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_rename_quantity_remaining_marketlisting_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='croptype',
            name='emoji',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
    ]
